from selenium.webdriver.common.by import By


class Locators:
    reg_link = (By.ID, "kc-register")
    registration = (By.XPATH, "//h1[contains(text(),'Регистрация')]")
    privat_data = (By.XPATH, "//p[contains(text(),'Личные данные')]")
    first_name = (By.NAME, "firstName")
    last_name = (By.NAME, "lastName")
    region = (By.XPATH, "//span[contains(text(),'Регион')]")
    reg_mail_phone = (By.XPATH, "//input[@id='address']")
    reg_password = (By.XPATH, "//input[@id='password']")
    confirm_password = (By.XPATH, "//input[@id='password-confirm']")
    btn_register = (By.NAME, "register")
    reg_user_agreement = (By.XPATH, "//a[@href='https://b2c.passport.rt.ru/sso-static/agreement/agreement.html']")
    reg_right_elements = (By.CLASS_NAME, "rt-input--rounded")
    reg_left_elements = (By.ID, "page-left")
    email_confirm = (By.XPATH, "//section/div/div/h1")
    phone_confirm = (By.XPATH, "//h1[contains(text(),'Подтверждение телефона')]")
    auth_tab_email = (By.XPATH, "//div[@id='t-btn-tab-mail']")
    auth_tab_phone = (By.XPATH, "//div[@id='t-btn-tab-phone']")
    auth_tab_login = (By.XPATH, "//div[@id='t-btn-tab-login']")
    auth_tab_ls = (By.XPATH, "//div[@id='t-btn-tab-ls']")
    auth_login = (By.XPATH, "//input[@id='username']")
    auth_password = (By.XPATH, "//input[@id='password']")
    private_cabinet = (By.XPATH, "//a[@id='lk-btn']")
    auth_btn_enter = (By.XPATH, "//button[@id='kc-login']")
    auth_page_left = (By.ID, "page-left")
    auth_page_right = (By.CLASS_NAME, "rt-tabs.rt-tabs--orange.rt-tabs--small.tabs-input-container__tabs")
    placeholder_name = (By.CLASS_NAME, "rt-input__placeholder")
    placeholder_email_passw = (By.XPATH, '//span[@class="rt-input__mask-start"]')
